### ISSUE TITLE
Feature: Valorant Function

### ISSUE THREAD

**Issue by nakashimas** [nakashimas/ggpython#1]
## OVERVIEW

Create function to get Valorant info.

## METHOD

Scraping

## TASK

- [x] get_summary(self, user_name, user_tag) -> dict
- [x] get_match_summary(self, user_name, user_tag, mode = "unrated") -> dict
- [x] get_pc_summary(self, user_name, user_tag, mode = "unrated") -> list
- [x] get_pc_result(self, user_name, user_tag, mode = "unrated") -> dict
- [x] get_map_result(self, user_name, user_tag, mode = "unrated") -> dict
- [x] get_weapon_result(self, user_name, user_tag, mode = "unrated") -> dict
- [x] get_award_result(self, user_name, user_tag) -> dict
- [x] get_custom_url_list(self, user_name, user_tag, n_match = None) -> list 
- [x] get_custom_result(self, user_name, user_tag, n_match = None) -> dict

## NOTE

`get_pc_url_list`は機能しないため実装を飛ばす
`get_award_result`は機能しないため実装を飛ばす

## REFERENCE

参考文献なし

**Comment by nakashimas** [comment]
IMPLEMENTATION NOTES
--------------------------------

## SUMMARY

データの形状が合わない問題

in get_custom_result(self, user_name, user_tag, n_match = None) -> list

## REPRODUCE

古いカスタムのデータや、中断したマッチを参照すると情報が少ない

## ACTUAL RESULTS

観測できる形状の差

<html>
<body>


Players | Current Rank | ACS | K | D | A | +/- | K/D
-- | -- | -- | -- | -- | -- | -- | --



</body>
</html>

## EXPECTED RESULTS

フルで取得できるもの

<html>
<body>


Players | Current Rank | ACS | K | D | A | +/- | K/D | ADR | HS% | FK | FD | MK | Econ
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --



</body>
</html>

## NOTE

キーを設定する基準をtable headerにすることで解決できる  
応急処置として例外処理を挟んで処理を飛ばした

以下でも同様の問題が発生する可能性あり

get_match_result() -> list
